version: '3.8'
services:
  serveur-app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app:delegated
    environment:
      - UVICORN_CMD=uvicorn main:app --host 0.0.0.0 --port 8000
    restart: unless-stopped
